name: CI

on: [push, repository_dispatch, pull_request]

jobs:
  jq:
    runs-on: ubuntu-latest
    steps:
      - name: install jq
        run: |
          sudo apt update
          sudo apt install -y jq
      - run: echo '[1,2,3]' | jq '.'
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role:
          - name: hoge
            repo: 'ho/ge'
          - name: fuga
            repo: 'fu/ga'
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Run a one-line script
        run: echo Hello, world! build ${{ matrix.role.name }}
      - name: touch
        run: touch ${{ matrix.role.name }}.txt
      - name: write
        run: echo ${{ matrix.role.repo }} >> ${{ matrix.role.name }}.txt

  hoge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - if: github.event.client_payload
        uses: actions/checkout@v2.3.2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Run a one-line script
        run: echo Hello, world! hoge
      - run: cat $GITHUB_EVENT_PATH
      - run: ls -al

  fuga:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - id: echo
        name: run shell
        run: |
          branch=`./demo.sh`
          echo "::set-output name=branch::$branch"
      - if: "steps.echo.outputs.branch"
        run: echo ${{ steps.echo.outputs.branch }}
      - id: seconds
        name: out seconds
        run: |
          sec=`./seconds.sh`
          echo "::set-output name=seconds::$sec"
      - if: "steps.seconds.outputs.sec == 0"
        run: echo 'divisible 2'
      - if: "steps.seconds.outputs.sec == 1"
        run: echo 'not divisible 2'
      - run: echo "${{ toJSON(job) }}"

  fuga2:
    runs-on: ubuntu-latest
    needs: fuga
    steps:
      - uses: actions/checkout@v2.3.2
      - name: echo steps
        run: echo ${{ toJSON(steps) }}

  piyo:
    if: "github.event_name != 'pull_request' || !startsWith(github.head_ref, 'versionup')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: echo head_ref
        run: echo ${{ github.head_ref }}
      - name: echo head_ref
        run: echo ${{ startsWith(github.head_ref, 'versionup/') }}

  notify:
    if: always()
    needs: [fuga2, piyo, hoge, jq]
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - run: echo ${{ env.WORKFLOW_CONCLUSION }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run:
          bash slack.sh ${{ env.WORKFLOW_CONCLUSION }} \
                        ${{ github.workflow }} \
                        ${{ github.actor }} \
                        ${{ github.event_name }} \
                        ${{ github.action }} \
                        ${{ github.run_id }} \
                        ${{ github.event.repository.url }} \
                        ${{ github.event.sender.avatar_url }} \
                        ${{ github.repository }} \
                        ${{ github.ref }} \
                        ${{ github.sha }} \
                        ${{ github.event.head_commit.message }}
