name: dynamic matrix

on: [push]

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: make values
        id: set-matrix
        run: |
          echo '["hoge","fuga"]' | jq -c
          matrix=$(echo '["hoge","fuga"]' | jq -c)
          echo "::set-output name=matrix::${matrix}"

  debug:
    needs: matrix
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ matrix.values.value }}
  execute:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        values: ${{fromJson(needs.matrix.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.values.value }}
