name: dynamic matrix

on:
  push:
  workflow_dispatch:

jobs:
  set-matrix-with-script:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.set-matrix.outputs.result }}
    steps:
      - uses: actions/github-script@v3
        id: set-matrix
        with:
          script: |
            const eventName = context.payload.event;
            const tags = ['a','b'];
            core.info(JSON.stringify(context), null, '  ');
            core.info(JSON.stringify(github), null, '  ')
            return (eventName === 'workflow_dispatch' || eventName === 'schedule') ? [...tags, 'all'] : tags;

  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      something: ${{ steps.set-matrix.outputs.value }}
    steps:
      - name: make values
        id: set-matrix
        run: |
          echo '["hoge","fuga"]' | jq -c
          list=$(echo '["hoge","fuga"]' | jq -c)
          echo "::set-output name=value::${list}"

  execute1:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hoge: ${{fromJson(needs.set-matrix.outputs.something)}}
    steps:
      - run: echo ${{ matrix.hoge }}

  execute2:
    needs: set-matrix-with-script
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hoge: ${{fromJson(needs.set-matrix-with-script.outputs.tags)}}
    steps:
      - run: echo ${{ matrix.hoge }}
