name: dynamic matrix

on:
  push:
  workflow_dispatch:

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.set-matrix.outputs.result }}
    steps:
      - uses: actions/github-script@v6.4.0
        id: set-matrix
        with:
          script: |
            const eventName = context.eventName;
            const tags = ['a','b'];
            core.info(JSON.stringify(context), null, '  ');
            core.info(JSON.stringify(github), null, '  ')
            console.log(eventName);
            return (eventName === 'workflow_dispatch' || eventName === 'schedule') ? [...tags, 'all'] : tags;

  execute:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hoge: ${{fromJson(needs.set-matrix.outputs.tags)}}
    steps:
      - run: echo ${{ matrix.hoge }}
