name: Manual Input And Scheduled
on:
  push:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      date:
        description: 'date'
        required: true

jobs:
  printDate:
    runs-on: ubuntu-latest
    steps:
    - name: input date
      run: |
        input_date=${{ github.event.inputs.date }}
        if [[ -z "$input_date" ]]; then
          start_date=$(date -d "1 day ago" +"%Y-%m-01")
        else
          start_date=$(echo $input_date)
        fi

        echo $start_date


