name: pip

on: push

jobs:
  pip:
    runs-on: ubuntu-latest
    steps:
      - name: install ansible-lint
        run: |
          sudo apt-get install python3-setuptools
          python3 -m pip install ansible-lint
