name: renovate

on:
  push:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v1.0.0
        with:
          configurationFile: renovate.json
          token: ${{ secrets.PERSONAL_TOKEN }}

