name: renovate

on:
  push:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v19.239.11
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.PERSONAL_TOKEN }}

