name: renovate

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v24.108.0
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.PERSONAL_TOKEN }}

