name: slack

on: push

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hoge'

  incomming_webhook:
    runs-on: ubuntu-latest
    needs: sample
    if: always()
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: technote-space/workflow-conclusion-action@v1
      - name: slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run:
          bash slack.sh ${{ env.WORKFLOW_CONCLUSION }} \
                        ${{ github.workflow }} \
                        ${{ github.actor }} \
                        ${{ github.event_name }} \
                        ${{ github.action }} \
                        ${{ github.run_id }} \
                        ${{ github.event.repository.url }} \
                        ${{ github.event.sender.avatar_url }} \
                        ${{ github.repository }} \
                        ${{ github.ref }} \
                        ${{ github.sha }} \
                        ${{ github.event.head_commit.message }}
