name: slack

on: push

jobs:
  incomming_webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - run: |
          echo $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH
          cp $GITHUB_EVENT_PATH event.json
      - uses: actions/upload-artifact@v1
        with:
          name: event.json
          path: event.json

      - run: ls -al
      - name: success
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run:
          bash slack.sh ${{ github.workflow }} \
                        ${{ github.actor }} \
                        ${{ github.event_name }}
      - name: failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          bash slack.sh ${{ github.workflow }}
