name: slack

on: push

jobs:
  incomming_webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - run: ls hoge
      - run: ls -al
      - name: success
        if: success()
        run: echo 'success'
      - name: failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo 'failure'
          echo "${{ toJSON(job) }}"
          echo "${{ toJSON(github) }}" > event.json
      - uses: actions/upload-artifact@v1
        with:
          name: event.json
          path: event.json

