name: workflow_run sample

on:
  workflow_run:
    workflows: ["CI", "pip", "sample"]
    branches: [master]
    types:
      - completed
jobs:
  workflow_result:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
