name: workflow result notification

on: [push, workflow_dispatch]

jobs:
  job-a1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role:
          - name: matrix-a
          - name: matrix-b
    steps:
      - run: sleep 1
      - run: exit 0

  job-a2:
    runs-on: ubuntu-latest
    needs: [job-a1]
    steps:
      - run: sleep 2
      - run: exit 0
  job-b:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5
      - run: exit 1

  slack-notify:
    if: always()
    needs: [job-a2, job-b]
    name: workflow notification to slack
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
